name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Bundle JAR
        run: ./gradlew shadowJar
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/
      - name: Run the JAR
        run: java -jar build/libs/*.jar
